---
  title: AI Preferences Working Group Materials
  description: Meeting agendas, minutes, slides, and other things
  remote_theme: ietf-wg-aipref/theme@main
  titles_from_headings:
    enabled:     true
    strip_title: true
    collections: false